# # ./k8s/overlays/dev/frontend-app-deployment-patch.yaml

# apiVersion: apps/v1
# kind: Service
# metadata:
#   name: frontend-app-service

# # k8s/overlays/dev/app/frontend-app-deployment-patch.yaml