import Head from 'next/head';
import React from 'react';
export type SeoProps = {
  title: string;
};

export const Seo = ({ title }: SeoProps) => {
  return (
    <Head>
      <title>{title}</title>
      <meta name="description" content="Generated by create next app" />
      <meta name="viewport" content="width=device-width, initial-scale=1" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
  );
};
