export const DEFAULT_STALE_TIME = 3_600_000;

export const QUERY_KEYS = {
  WEB_PUSH_NOTIFICATIONS: 'web-push-notifications',
  GET_CATEGORIES: 'get-categories',
  GET_STORIES: 'get-stories',
  GET_STORYLINES_BY_STORY_SLUG: 'get-storylines-by-story-slug',
  LIKE_STORY: 'like-story',
  UNLIKE_STORY: 'unlike-story',
  DISLIKE_STORY: 'dislike-story',
  UNDISLIKE_STORY: 'undislike-story',
  GET_STORIES_BY_HASHTAG: 'get-stories-by-hashtag',
  GET_STORIES_BY_CATEGORY: 'get-stories-by-category',
  GET_STORYLINES: 'get-storylines',
  GET_USERS: 'get-users',
  GET_BOOKMARKS: 'get-bookmarks',
  ADD_BOOKMARK: 'add-bookmark',
  ADD_FEEDBACK: 'get-feedbacks',
  GET_FEEDBACKS: 'add-feedback',
  DELETE_BOOKMARK: 'delete-bookmark',
  GET_HASHTAGS: 'get-hashtags',
  GET_USER_SETTINGS: 'get-settings',
  FOLLOW_USER: 'follow-user',
  UPDATE_USER_SETTINGS: 'get-settings',
  UPDATE_USER_PROFILE_INFO: 'put-user-profile-info',
  UPDATE_USER_PASSWORD: 'put-user-password',
  SYNC_ANALYTICS: 'analytics-sync',
  AUTH_USER: 'auth-user',
  ADD_BATCH_ANALYTICS: 'add-batch-analytics',
  ADD_ANALYTICS: 'add-analytics',
  GET_SUPPORT_ARTICLES: 'get-support-articles',
  GET_SUPPORT_CATEGORIES: 'get-support-categories',
  GET_LEGAL_DOCUMENT: 'get-legal-document',
};

//Path: src/config/query.ts
