apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../base/app/

patches:
  - path: frontend-app-deployment-patch.yaml
    target:
      kind: Deployment
      name: frontend-app

  - path: frontend-app-service-patch.yaml
    target:
      kind: Service
      name: frontend-app-service

images:
  - name: web-app-image
    newName: europe-west2-docker.pkg.dev/media-app-418813/media-app-repo/frontend-app-image
    newTag: staging-0.0.1

# commonLabels:
#   app: frontend-app

# k8s/overlays/dev/app/kustomization.yaml