apiVersion: v1
data:
  ENV_VARIABLE: production_server_only_variable
  NEXT_PUBLIC_API_MOCKING: "false"
  NEXT_PUBLIC_API_URL: https://api.mediaapp.local/api
  NEXT_PUBLIC_APP_SUPPORT_VERSION: v1.0
  NEXT_PUBLIC_APP_URL: https://app.mediaapp.local
  NEXT_PUBLIC_DEBUG: "false"
  NEXT_PUBLIC_ENV_VARIABLE: production_public_variable
  NEXT_PUBLIC_SHOW_LOGGER: "false"
  NEXT_SERVER_API_URL: http://web-app-service:8000/api
  NEXTAUTH_SECRET: nextauth-secret
  NEXTAUTH_URL: https://app.mediaapp.local
kind: ConfigMap
metadata:
  name: frontend-app-configmap

# k8s/base/app/frontend-app-configmap.yaml