apiVersion: v1
kind: Service
metadata:
  name: frontend-app-service
spec:
  type: NodePort
  selector:
    app: frontend-app
  ports:
    - name: "3000"
      protocol: TCP
      port: 3000
      targetPort: 3000
# k8s/base/app/web-app-service.yaml