apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: frontend-app-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

# k8s/base/app/frontend-app-pvc.yaml