name: CI Pipeline

on:
  push:
    branches:
      - staging
  pull_request:
    branches:
      - staging
env:
  DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
  DOCKER_HUB_TOKEN: ${{ secrets.DOCKER_HUB_TOKEN }}
  REPOSITORY_NAME: mediaapp

jobs:
  build:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: staging # Ensure the staging branch is checked out

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_HUB_TOKEN }}" | docker login -u "${{ secrets.DOCKER_HUB_USERNAME }}" --password-stdin
      # Build and Push Backend
      - name: Build Backend Docker image
        run: |
          docker build --platform linux/amd64 -t ${{ secrets.DOCKER_HUB_USERNAME }}/${{env.REPOSITORY_NAME}}:frontend-app-latest -f Dockerfile.dev .

      - name: Push Backend Docker image to Docker Hub
        run: |
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/${{env.REPOSITORY_NAME}}:frontend-app-latest

# .github/workflows/ci-docker-hub.yml
