apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - app/
namespace: staging

configMapGenerator:
  - name: frontend-app-configmap
    behavior: merge
    envs:
      - app/staging.properties
secretGenerator:
  - name: frontend-app-secret
    behavior: merge
    envs:
      - app/secrets.env
commonLabels:
  environment: staging


# k8s/overlays/dev/kustomization.yaml